var schoolList = [
    {
      id:"01",
      name:"世新大學",
      colorHead:"#E97DAE",
      colorEnd: "#F7E7F0",
      type:"藝術/傳播/設計",
      link:"https://student.overseas.ncnu.edu.tw/quota/index.html?school=48&group=all&keyword=&first-group=true&second-group=true&third-group=true",
      email:"",
      messenger:"https://m.me/ShihHsinU",
      schoolid: "48",
    },
    {
      id:"02",
      name:"國立臺北藝術大學",
      colorHead:"#E97DAE",
      colorEnd: "#F7E7F0",
      type:"藝術/傳播/設計",
      link:"https://student.overseas.ncnu.edu.tw/quota/index.html?school=33&group=all&keyword=&first-group=true&second-group=true&third-group=true",
      email:"",
      messenger:"",
      schoolid: "33",
    },
    {
      id:"03",
      name:"國立臺中科技大學",
      colorHead:"#E97DAE",
      colorEnd: "#F7E7F0",
      type:"藝術/傳播/設計",
      link:"https://student.overseas.ncnu.edu.tw/quota/index.html?school=82&group=all&keyword=&first-group=true&second-group=true&third-group=true",
      email:"",
      messenger:"",
      schoolid: "82",
    },
    {
      id:"04",
      name:"中國科技大學",
      colorHead:"#E97DAE",
      colorEnd: "#F7E7F0",
      type:"藝術/傳播/設計",
      link:"https://student.overseas.ncnu.edu.tw/quota/index.html?school=98&group=all&keyword=&first-group=true&second-group=true&third-group=true",
      email:"csec1036@cute.edu.tw",
      messenger:"",
      schoolid: "98",
    },
    {
      id:"05",
      name:"國立臺灣大學",
      colorHead:"#83CEEB",
      colorEnd: "#D0EBF4",
      type:"大學系統",
      link:"https://student.overseas.ncnu.edu.tw/quota/index.html?school=01&group=all&keyword=&first-group=true&second-group=true&third-group=true",
      email:"",
      messenger:"",
      schoolid: "01",
    },
    {
      id:"06",
      name:"國立臺灣師範大學",
      colorHead:"#83CEEB",
      colorEnd: "#D0EBF4",
      type:"大學系統",
      link:"https://student.overseas.ncnu.edu.tw/quota/index.html?school=07&group=all&keyword=&first-group=true&second-group=true&third-group=true",
      email:"",
      messenger:"https://m.me/joinmenups",
      schoolid: "07",
    },
    {
      id:"07",
      name:"國立臺灣科技大學",
      colorHead:"#83CEEB",
      colorEnd: "#D0EBF4",
      type:"大學系統",
      link:"https://student.overseas.ncnu.edu.tw/quota/index.html?school=71&group=all&keyword=&first-group=true&second-group=true&third-group=true",
      email:"lydia@mail.ntust.edu.tw",
      messenger:"",
      schoolid: "71",
    },
    {
      id:"08",
      name:"國立臺北科技大學",
      colorHead:"#83CEEB",
      colorEnd: "#D0EBF4",
      type:"大學系統",
      link:"https://student.overseas.ncnu.edu.tw/quota/index.html?school=73&group=all&keyword=&first-group=true&second-group=true&third-group=true",
      email:"intstudy@ntut.edu.tw",
      messenger:"https://m.me/issoiataipeitech",
      schoolid: "73",
    },
    {
      id:"09",
      name:"國立臺北大學",
      colorHead:"#83CEEB",
      colorEnd: "#D0EBF4",
      type:"大學系統",
      link:"https://student.overseas.ncnu.edu.tw/quota/index.html?school=10&group=all&keyword=&first-group=true&second-group=true&third-group=true",
      email:"",
      messenger:"",
      schoolid: "10",
    },
    {
      id:"10",
      name:"國立中興大學",
      colorHead:"#83CEEB",
      colorEnd: "#D0EBF4",
      type:"大學系統",
      link:"https://student.overseas.ncnu.edu.tw/quota/index.html?school=05&group=all&keyword=&first-group=true&second-group=true&third-group=true",
      email:"kuan@nchu.edu.tw",
      messenger:"",
      schoolid: "05",
    },
    {
      id:"11",
      name:"國立中正大學",
      colorHead:"#83CEEB",
      colorEnd: "#D0EBF4",
      type:"大學系統",
      link:"https://student.overseas.ncnu.edu.tw/quota/index.html?school=06&group=all&keyword=&first-group=true&second-group=true&third-group=true",
      email:"",
      messenger:"https://m.me/CCUMacauHongKong",
      schoolid: "06",
    },
    {
      id:"12",
      name:"國立成功大學",
      colorHead:"#83CEEB",
      colorEnd: "#D0EBF4",
      type:"大學系統",
      link:"https://student.overseas.ncnu.edu.tw/quota/index.html?school=02&group=all&keyword=&first-group=true&second-group=true&third-group=true",
      email:"ciao@email.ncku.edu.tw",
      messenger:"",
      schoolid: "02",
    },
    {
      id:"13",
      name:"國立中山大學",
      colorHead:"#83CEEB",
      colorEnd: "#D0EBF4",
      type:"大學系統",
      link:"https://student.overseas.ncnu.edu.tw/quota/index.html?school=19&group=all&keyword=&first-group=true&second-group=true&third-group=true",
      email:"",
      messenger:"",
      schoolid: "19",
    },
    {
      id:"14",
      name:"高雄醫學大學",
      colorHead:"#83CEEB",
      colorEnd: "#D0EBF4",
      type:"大學系統",
      link:"https://student.overseas.ncnu.edu.tw/quota/index.html?school=67&group=all&keyword=&first-group=true&second-group=true&third-group=true",
      email:"",
      messenger:"https://m.me/116618852336483",
      schoolid: "67",
    },
    {
      id:"15",
      name:"崑山科技大學",
      colorHead:"#E97DAE",
      colorEnd: "#F7E7F0",
      type:"藝術/傳播/設計",
      link:"https://student.overseas.ncnu.edu.tw/quota/index.html?school=88&group=all&keyword=&first-group=true&second-group=true&third-group=true",
      email:"oiad@mail.ksu.edu.tw",
      messenger:"",
      schoolid: "88",
    },
    {
      id:"16",
      name:"黎明技術學院",
      colorHead:"#E97DAE",
      colorEnd: "#F7E7F0",
      type:"藝術/傳播/設計",
      link:"https://student.overseas.ncnu.edu.tw/quota/index.html?school=E4&group=all&keyword=&first-group=true&second-group=true&third-group=true",
      email:"ica@mail.lit.edu.tw",
      messenger:"",
      schoolid: "E4",
    },
    {
      id:"17",
      name:"朝陽科技大學",
      colorHead:"#E97DAE",
      colorEnd: "#F7E7F0",
      type:"藝術/傳播/設計",
      link:"https://student.overseas.ncnu.edu.tw/quota/index.html?school=86&group=all&keyword=&first-group=true&second-group=true&third-group=true",
      email:"",
      messenger:"",
      schoolid: "86",
    },
    {
      id:"18",
      name:"玄奘大學",
      colorHead:"#E97DAE",
      colorEnd: "#F7E7F0",
      type:"藝術/傳播/設計",
      link:"https://student.overseas.ncnu.edu.tw/quota/index.html?school=59&group=all&keyword=&first-group=true&second-group=true&third-group=true",
      email:"",
      messenger:"https://www.facebook.com/hcu.admissions.office/",
      schoolid: "59",
    },
    {
      id:"19",
      name:"南臺科技大學",
      colorHead:"#E97DAE",
      colorEnd: "#F7E7F0",
      type:"藝術/傳播/設計",
      link:"https://student.overseas.ncnu.edu.tw/quota/index.html?school=87&group=all&keyword=&first-group=true&second-group=true&third-group=true",
      email:"",
      messenger:"",
      schoolid: "87",
    },
    {
      id:"20",
      name:"大葉大學",
      colorHead:"#E97DAE",
      colorEnd: "#F7E7F0",
      type:"藝術/傳播/設計",
      link:"https://student.overseas.ncnu.edu.tw/quota/index.html?school=49&group=all&keyword=&first-group=true&second-group=true&third-group=true",
      email:"",
      messenger:"https://www.facebook.com/DAYEH.international",
      schoolid: "49",
    },
    {
      id:"21",
      name:"實踐大學",
      colorHead:"#E97DAE",
      colorEnd: "#F7E7F0",
      type:"藝術/傳播/設計",
      link:"https://student.overseas.ncnu.edu.tw/quota/index.html?school=40&group=all&keyword=&first-group=true&second-group=true&third-group=true",
      email:"",
      messenger:"https://m.me/usckh",
      schoolid: "40",
    },
    {
      id:"22",
      name:"亞洲大學",
      colorHead:"#E97DAE",
      colorEnd: "#F7E7F0",
      type:"藝術/傳播/設計",
      link:"https://student.overseas.ncnu.edu.tw/quota/index.html?school=47&group=all&keyword=&first-group=true&second-group=true&third-group=true",
      email:"ciae@gm.asia.edu.tw",
      messenger:"",
      schoolid: "47",
    },
    {
      id:"23",
      name:"龍華科技大學",
      colorHead:"#E97DAE",
      colorEnd: "#F7E7F0",
      type:"藝術/傳播/設計",
      link:"https://student.overseas.ncnu.edu.tw/quota/index.html?school=D8&group=all&keyword=&first-group=true&second-group=true&third-group=true",
      email:"icsc@gm.lhu.edu.tw",
      messenger:"",
      schoolid: "D8",
    },
    {
      id:"24",
      name:"華梵大學",
      colorHead:"#E97DAE",
      colorEnd: "#F7E7F0",
      type:"藝術/傳播/設計",
      link:"https://student.overseas.ncnu.edu.tw/quota/index.html?school=62&group=all&keyword=&first-group=true&second-group=true&third-group=true",
      email:"ad@cc.hfu.edu.tw",
      messenger:"",
      schoolid: "62",
    },
    {
      id:"25",
      name:"明志科技大學",
      colorHead:"#E97DAE",
      colorEnd: "#F7E7F0",
      type:"藝術/傳播/設計",
      link:"https://student.overseas.ncnu.edu.tw/quota/index.html?school=97&group=all&keyword=&first-group=true&second-group=true&third-group=true",
      email:"cia@mail.mcut.edu.tw",
      messenger:"",
      schoolid: "97",
    },
    {
      id:"26",
      name:"華夏科技大學",
      colorHead:"#E97DAE",
      colorEnd: "#F7E7F0",
      type:"藝術/傳播/設計",
      link:"https://student.overseas.ncnu.edu.tw/quota/index.html?school=D3&group=all&keyword=&first-group=true&second-group=true&third-group=true",
      email:"",
      messenger:"",
      schoolid: "D3",
    },
    {
      id:"27",
      name:"大同大學",
      colorHead:"#E97DAE",
      colorEnd: "#F7E7F0",
      type:"藝術/傳播/設計",
      link:"https://student.overseas.ncnu.edu.tw/quota/index.html?school=63&group=all&keyword=&first-group=true&second-group=true&third-group=true",
      email:"admission@ttu.edu.tw",
      messenger:"",
      schoolid: "63",
    },
    {
      id:"28",
      name:"弘光科技大學",
      colorHead:"#F6D87E",
      colorEnd: "#F4E1B7",
      type:"醫藥/治療/護理",
      link:"https://student.overseas.ncnu.edu.tw/quota/index.html?school=93&group=all&keyword=&first-group=true&second-group=true&third-group=true",
      email:"",
      messenger:"",
      schoolid: "93",
    },
    {
      id:"29",
      name:"嘉南藥理大學",
      colorHead:"#F6D87E",
      colorEnd: "#F4E1B7",
      type:"醫藥/治療/護理",
      link:"https://student.overseas.ncnu.edu.tw/quota/index.html?school=90&group=all&keyword=&first-group=true&second-group=true&third-group=true",
      email:"",
      messenger:"https://m.me/chungcheng.lin",
      schoolid: "90",
    },
    {
      id:"30",
      name:"臺北醫學大學",
      colorHead:"#F6D87E",
      colorEnd: "#F4E1B7",
      type:"醫藥/治療/護理",
      link:"https://student.overseas.ncnu.edu.tw/quota/index.html?school=69&group=all&keyword=&first-group=true&second-group=true&third-group=true",
      email:"admission@tmu.edu.tw",
      messenger:"",
      schoolid: "69",
    },
    {
      id:"31",
      name:"文藻外語大學",
      colorHead:"#EC7C7B",
      colorEnd: "#F5CECF",
      type:"金融/經濟/管理",
      link:"https://student.overseas.ncnu.edu.tw/quota/index.html?school=B2&group=all&keyword=&first-group=true&second-group=true&third-group=true",
      email:"overseas.student@mail.wzu.edu.tw",
      messenger:"",
      schoolid: "B2",
    },
    {
      id:"32",
      name:"國立中央大學",
      colorHead:"#EC7C7B",
      colorEnd: "#F5CECF",
      type:"金融/經濟/管理",
      link:"https://student.overseas.ncnu.edu.tw/quota/index.html?school=15&group=all&keyword=&first-group=true&second-group=true&third-group=true",
      email:"eileen@ncu.edu.tw  ",
      messenger:"",
      schoolid: "15",
    },
    {
      id:"33",
      name:"國立臺灣海洋大學",
      colorHead:"#EE7A1A",
      colorEnd: "#F9D7BE",
      type:"海洋/森林/農業",
      link:"https://student.overseas.ncnu.edu.tw/quota/index.html?school=09&group=all&keyword=&first-group=true&second-group=true&third-group=true",
      email:"",
      messenger:"",
      schoolid: "09",
    },
    {
      id:"34",
      name:"國立宜蘭大學",
      colorHead:"#EE7A1A",
      colorEnd: "#F9D7BE",
      type:"海洋/森林/農業",
      link:"https://student.overseas.ncnu.edu.tw/quota/index.html?school=14&group=all&keyword=&first-group=true&second-group=true&third-group=true",
      email:"isa@niu.edu.tw",
      messenger:"",
      schoolid: "14",
    },
    {
      id:"35",
      name:"國立嘉義大學",
      colorHead:"#EE7A1A",
      colorEnd: "#F9D7BE",
      type:"海洋/森林/農業",
      link:"https://student.overseas.ncnu.edu.tw/quota/index.html?school=03&group=all&keyword=&first-group=true&second-group=true&third-group=true",
      email:"chiaying506@mail.ncyu.edu.tw",
      messenger:"",
      schoolid: "03",
    },
    {
      id:"36",
      name:"中國文化大學",
      colorHead:"#EE7A1A",
      colorEnd: "#F9D7BE",
      type:"海洋/森林/農業",
      link:"https://student.overseas.ncnu.edu.tw/quota/index.html?school=36&group=all&keyword=&first-group=true&second-group=true&third-group=true",
      email:"",
      messenger:"",
      schoolid: "36",
    },
    {
      id:"37",
      name:"國立暨南國際大學",
      colorHead:"#B195C5",
      colorEnd: "#DFD0E5",
      type:"文史/心理/教育",
      link:"https://student.overseas.ncnu.edu.tw/quota/index.html?school=04&group=all&keyword=&first-group=true&second-group=true&third-group=true",
      email:"",
      messenger:"",
      schoolid: "04",
    },
    {
      id:"38",
      name:"國立東華大學",
      colorHead:"#B195C5",
      colorEnd: "#DFD0E5",
      type:"文史/心理/教育",
      link:"https://student.overseas.ncnu.edu.tw/quota/index.html?school=08&group=all&keyword=&first-group=true&second-group=true&third-group=true",
      email:"admission@gms.ndhu.edu.tw",
      messenger:"",
      schoolid: "08",
    },
    {
      id:"39",
      name:"國立屏東大學",
      colorHead:"#B195C5",
      colorEnd: "#DFD0E5",
      type:"文史/心理/教育",
      link:"https://student.overseas.ncnu.edu.tw/quota/index.html?school=F0&group=all&keyword=&first-group=true&second-group=true&third-group=true",
      email:"",
      messenger:"",
      schoolid: "F0",
    },
    {
      id:"40",
      name:"國立彰化師範大學",
      colorHead:"#B195C5",
      colorEnd: "#DFD0E5",
      type:"文史/心理/教育",
      link:"https://student.overseas.ncnu.edu.tw/quota/index.html?school=23&group=all&keyword=&first-group=true&second-group=true&third-group=true",
      email:"",
      messenger:"",
      schoolid: "23",
    },
    {
      id:"41",
      name:"慈濟科技大學",
      colorHead:"#F6D87E",
      colorEnd: "#F4E1B7",
      type:"醫藥/治理/護理",
      link:"https://student.overseas.ncnu.edu.tw/quota/index.html?school=B4&group=all&keyword=&first-group=true&second-group=true&third-group=true",
      email:"",
      messenger:"https://www.facebook.com/groups/1455052831382971/",
      schoolid: "B4",
    },
    {
      id:"42",
      name:"中臺科技大學",
      colorHead:"#F6D87E",
      colorEnd: "#F4E1B7",
      type:"醫藥/治理/護理",
      link:"https://student.overseas.ncnu.edu.tw/quota/index.html?school=A3&group=all&keyword=&first-group=true&second-group=true&third-group=true",
      email:"",
      messenger:"",
      schoolid: "A3",
    },
    {
      id:"43",
      name:"長庚科技大學",
      colorHead:"#F6D87E",
      colorEnd: "#F4E1B7",
      type:"醫藥/治理/護理",
      link:"https://student.overseas.ncnu.edu.tw/quota/index.html?school=E5&group=all&keyword=&first-group=true&second-group=true&third-group=true",
      email:"acade@mail.cgu.edu.tw",
      messenger:"",
      schoolid: "E5",
    },
    {
      id:"44",
      name:"長庚大學",
      colorHead:"#F6D87E",
      colorEnd: "#F4E1B7",
      type:"醫藥/治理/護理",
      link:"https://student.overseas.ncnu.edu.tw/quota/index.html?school=65&group=all&keyword=&first-group=true&second-group=true&third-group=true",
      email:"",
      messenger:"",
      schoolid: "65",
    },
    {
      id:"45",
      name:"大仁科技大學",
      colorHead:"#F6D87E",
      colorEnd: "#F4E1B7",
      type:"醫藥/治理/護理",
      link:"https://student.overseas.ncnu.edu.tw/quota/index.html?school=99&group=all&keyword=&first-group=true&second-group=true&third-group=true",
      email:"",
      messenger:"",
      schoolid: "99",
    },
    {
      id:"46",
      name:"輔英科技大學",
      colorHead:"#F6D87E",
      colorEnd: "#F4E1B7",
      type:"醫藥/治理/護理",
      link:"https://student.overseas.ncnu.edu.tw/quota/index.html?school=92&group=all&keyword=&first-group=true&second-group=true&third-group=true",
      email:"oia@fy.edu.tw",
      messenger:"",
      schoolid: "92",
    },
    {
      id:"47",
      name:"國立臺北護理健康大學",
      colorHead:"#F6D87E",
      colorEnd: "#F4E1B7",
      type:"醫藥/治理/護理",
      link:"https://student.overseas.ncnu.edu.tw/quota/index.html?school=85&group=all&keyword=&first-group=true&second-group=true&third-group=true",
      email:"yuling@ntunhs.edu.tw",
      messenger:"",
      schoolid: "85",
    },
    {
      id:"48",
      name:"中國醫藥大學",
      colorHead:"#F6D87E",
      colorEnd: "#F4E1B7",
      type:"醫藥/治理/護理",
      link:"https://student.overseas.ncnu.edu.tw/quota/index.html?school=68&group=all&keyword=&first-group=true&second-group=true&third-group=true",
      email:"intelstu@mail.cmu.edu.tw",
      messenger:"",
      schoolid: "68",
    },
    {
      id:"49",
      name:"中山醫學大學",
      colorHead:"#F6D87E",
      colorEnd: "#F4E1B7",
      type:"醫藥/治理/護理",
      link:"https://student.overseas.ncnu.edu.tw/quota/index.html?school=66&group=all&keyword=&first-group=true&second-group=true&third-group=true",
      email:"",
      messenger:"",
      schoolid: "66",
    },
    {
      id:"50",
      name:"元培醫事科技大學",
      colorHead:"#F6D87E",
      colorEnd: "#F4E1B7",
      type:"醫藥/治理/護理",
      link:"https://student.overseas.ncnu.edu.tw/quota/index.html?school=A6&group=all&keyword=&first-group=true&second-group=true&third-group=true",
      email:"ruohan@mail.ypu.edu.tw",
      messenger:"",
      schoolid: "A6",
    },
    {
      id:"51",
      name:"環球科技大學",
      colorHead:"#5DA37F",
      colorEnd: "#E5F2E9",
      type:"餐飲/休閒/運動",
      link:"https://student.overseas.ncnu.edu.tw/quota/index.html?school=C6&group=all&keyword=&first-group=true&second-group=true&third-group=true",
      email:"cia@twu.edu.tw",
      messenger:"",
      schoolid: "C6",
    },
    {
      id:"52",
      name:"明道大學",
      colorHead:"#5DA37F",
      colorEnd: "#E5F2E9",
      type:"餐飲/休閒/運動",
      link:"https://student.overseas.ncnu.edu.tw/quota/index.html?school=54&group=all&keyword=&first-group=true&second-group=true&third-group=true",
      email:"",
      messenger:"https://www.facebook.com/MDU2001/",
      schoolid: "54",
    },
    {
      id:"53",
      name:"國立臺南大學",
      colorHead:"#5DA37F",
      colorEnd: "#E5F2E9",
      type:"餐飲/休閒/運動",
      link:"https://student.overseas.ncnu.edu.tw/quota/index.html?school=18&group=all&keyword=&first-group=true&second-group=true&third-group=true",
      email:"",
      messenger:"https://m.me/NUTNOIA",
      schoolid: "18",
    },
    {
      id:"54",
      name:"景文科技大學",
      colorHead:"#5DA37F",
      colorEnd: "#E5F2E9",
      type:"餐飲/休閒/運動",
      link:"https://student.overseas.ncnu.edu.tw/quota/index.html?school=B3&group=all&keyword=&first-group=true&second-group=true&third-group=true",
      email:"",
      messenger:"https://m.me/just1798",
      schoolid: "B3",
    },
    {
      id:"55",
      name:"國立高雄師範大學",
      colorHead:"#DED5C6",
      colorEnd: "#F6F1EB",
      type:"綜合展區",
      link:"https://student.overseas.ncnu.edu.tw/quota/index.html?school=27&group=all&keyword=&first-group=true&second-group=true&third-group=true",
      email:"",
      messenger:"",
      schoolid: "27",
    },
    {
      id:"56",
      name:"台南應用科技大學",
      colorHead:"#DED5C6",
      colorEnd: "#F6F1EB",
      type:"綜合展區",
      link:"https://student.overseas.ncnu.edu.tw/quota/index.html?school=A4&group=all&keyword=&first-group=true&second-group=true&third-group=true",
      email:"emoiss@gm.tut.edu.tw",
      messenger:"",
      schoolid: "A4",
    },
    {
      id:"57",
      name:"天主教輔仁大學",
      colorHead:"#DED5C6",
      colorEnd: "#F6F1EB",
      type:"綜合展區",
      link:"https://student.overseas.ncnu.edu.tw/quota/index.html?school=45&group=all&keyword=&first-group=true&second-group=true&third-group=true",
      email:"048767@mail.fju.edu.tw",
      messenger:"",
      schoolid: "45",
    },
    {
      id:"58",
      name:"淡江大學",
      colorHead:"#DED5C6",
      colorEnd: "#F6F1EB",
      type:"綜合展區",
      link:"https://student.overseas.ncnu.edu.tw/quota/index.html?school=37&group=all&keyword=&first-group=true&second-group=true&third-group=true",
      email:"",
      messenger:"",
      schoolid: "37",
    },
    {
      id:"59",
      name:"國立臺中教育大學",
      colorHead:"#DED5C6",
      colorEnd: "#F6F1EB",
      type:"綜合展區",
      link:"https://student.overseas.ncnu.edu.tw/quota/index.html?school=26&group=all&keyword=&first-group=true&second-group=true&third-group=true",
      email:"ici@gm.ntcu.edu.tw",
      messenger:"",
      schoolid: "26",
    },
    {
      id:"60",
      name:"靜宜大學",
      colorHead:"#DED5C6",
      colorEnd: "#F6F1EB",
      type:"綜合展區",
      link:"https://student.overseas.ncnu.edu.tw/quota/index.html?school=42&group=all&keyword=&first-group=true&second-group=true&third-group=true",
      email:"",
      messenger:"",
      schoolid: "42",
    },
    {
      id:"61",
      name:"致理科技大學",
      colorHead:"#DED5C6",
      colorEnd: "#F6F1EB",
      type:"綜合展區",
      link:"https://student.overseas.ncnu.edu.tw/quota/index.html?school=C3&group=all&keyword=&first-group=true&second-group=true&third-group=true",
      email:"",
      messenger:"https://zh-tw.facebook.com/chihleefans",
      schoolid: "C3",
    },
    {
      id:"62",
      name:"南華大學",
      colorHead:"#DED5C6",
      colorEnd: "#F6F1EB",
      type:"綜合展區",
      link:"https://student.overseas.ncnu.edu.tw/quota/index.html?school=60&group=all&keyword=&first-group=true&second-group=true&third-group=true",
      email:"",
      messenger:"",
      schoolid: "60",
    },
    {
      id:"63",
      name:"義守大學",
      colorHead:"#DED5C6",
      colorEnd: "#F6F1EB",
      type:"綜合展區",
      link:"https://student.overseas.ncnu.edu.tw/quota/index.html?school=41&group=all&keyword=&first-group=true&second-group=true&third-group=true",
      email:"",
      messenger:"",
      schoolid: "41",
    },
    {
      id:"64",
      name:"逢甲大學",
      colorHead:"#DED5C6",
      colorEnd: "#F6F1EB",
      type:"綜合展區",
      link:"https://student.overseas.ncnu.edu.tw/quota/index.html?school=44&group=all&keyword=&first-group=true&second-group=true&third-group=true",
      email:"",
      messenger:"https://m.me/checkinatfcu",
      schoolid: "44",
    },
    {
      id:"65",
      name:"國立高雄科技大學",
      colorHead:"#DED5C6",
      colorEnd: "#F6F1EB",
      type:"綜合展區",
      link:"https://student.overseas.ncnu.edu.tw/quota/index.html?school=75&group=all&keyword=&first-group=true&second-group=true&third-group=true",
      email:"",
      messenger:"https://m.me/iloveocs",
      schoolid: "75",
    },
    {
      id:"66",
      name:"國立交通大學",
      colorHead:"#DED5C6",
      colorEnd: "#F6F1EB",
      type:"綜合展區",
      link:"https://student.overseas.ncnu.edu.tw/quota/index.html?school=11&group=all&keyword=&first-group=true&second-group=true&third-group=true",
      email:"admitphd@cc.nctu.edu.tw",
      messenger:"",
      schoolid: "11",
    },
    {
      id:"67",
      name:"東海大學",
      colorHead:"#DED5C6",
      colorEnd: "#F6F1EB",
      type:"綜合展區",
      link:"https://student.overseas.ncnu.edu.tw/quota/index.html?school=39&group=all&keyword=&first-group=true&second-group=true&third-group=true",
      email:"oir@thu.edu.tw",
      messenger:"",
      schoolid: "39",
    },
    {
      id:"68",
      name:"樹德科技大學",
      colorHead:"#DED5C6",
      colorEnd: "#F6F1EB",
      type:"綜合展區",
      link:"https://student.overseas.ncnu.edu.tw/quota/index.html?school=89&group=all&keyword=&first-group=true&second-group=true&third-group=true",
      email:"oica@stu.edu.tw",
      messenger:"",
      schoolid: "89",
    },
    {
      id:"69",
      name:"國立清華大學",
      colorHead:"#DED5C6",
      colorEnd: "#F6F1EB",
      type:"綜合展區",
      link:"https://student.overseas.ncnu.edu.tw/quota/index.html?school=17&group=all&keyword=&first-group=true&second-group=true&third-group=true",
      email:"adms@my.nthu.edu.tw",
      messenger:"",
      schoolid: "17",
    },
    {
      id:"70",
      name:"元智大學",
      colorHead:"#DED5C6",
      colorEnd: "#F6F1EB",
      type:"綜合展區",
      link:"https://student.overseas.ncnu.edu.tw/quota/index.html?school=57&group=all&keyword=&first-group=true&second-group=true&third-group=true",
      email:"iadept@saturn.yzu.edu.tw",
      messenger:"",
      schoolid: "57",
    },
    {
      id:"71",
      name:"萬能科技大學",
      colorHead:"#DED5C6",
      colorEnd: "#F6F1EB",
      type:"綜合展區",
      link:"https://student.overseas.ncnu.edu.tw/quota/index.html?school=96&group=all&keyword=&first-group=true&second-group=true&third-group=true",
      email:"cch680121@gmail.com",
      messenger:"",
      schoolid: "96",
    },
    {
      id:"72",
      name:"長榮大學",
      colorHead:"#DED5C6",
      colorEnd: "#F6F1EB",
      type:"綜合展區",
      link:"https://student.overseas.ncnu.edu.tw/quota/index.html?school=46&group=all&keyword=&first-group=true&second-group=true&third-group=true",
      email:"",
      messenger:"",
      schoolid: "46",
    },
    {
      id:"73",
      name:"國立臺東大學",
      colorHead:"#DED5C6",
      colorEnd: "#F6F1EB",
      type:"綜合展區",
      link:"https://student.overseas.ncnu.edu.tw/quota/index.html?school=20&group=all&keyword=&first-group=true&second-group=true&third-group=true",
      email:"",
      messenger:"https://www.messenger.com/t/100001875291637",
      schoolid: "20",
    },
    {
      id:"74",
      name:"佛光大學",
      colorHead:"#DED5C6",
      colorEnd: "#F6F1EB",
      type:"綜合展區",
      link:"https://student.overseas.ncnu.edu.tw/quota/index.html?school=64&group=all&keyword=&first-group=true&second-group=true&third-group=true",
      email:"",
      messenger:"",
      schoolid: "64",
    },
    {
      id:"75",
      name:"東吳大學",
      colorHead:"#DED5C6",
      colorEnd: "#F6F1EB",
      type:"綜合展區",
      link:"https://student.overseas.ncnu.edu.tw/quota/index.html?school=55&group=all&keyword=&first-group=true&second-group=true&third-group=true",
      email:"",
      messenger:"",
      schoolid: "55",
    },
    {
      id:"76",
      name:"臺北市立大學",
      colorHead:"#DED5C6",
      colorEnd: "#F6F1EB",
      type:"綜合展區",
      link:"https://student.overseas.ncnu.edu.tw/quota/index.html?school=E0&group=all&keyword=&first-group=true&second-group=true&third-group=true",
      email:"",
      messenger:"",
      schoolid: "E0",
    },
    {
      id:"77",
      name:"铭傳大學",
      colorHead:"#DED5C6",
      colorEnd: "#F6F1EB",
      type:"綜合展區",
      link:"https://student.overseas.ncnu.edu.tw/quota/index.html?school=38&group=all&keyword=&first-group=true&second-group=true&third-group=true",
      email:"",
      messenger:"",
      schoolid: "38",
    },
    {
      id:"78",
      name:"中華大學",
      colorHead:"#DED5C6",
      colorEnd: "#F6F1EB",
      type:"綜合展區",
      link:"https://student.overseas.ncnu.edu.tw/quota/index.html?school=50&group=all&keyword=&first-group=true&second-group=true&third-group=true",
      email:"international@chu.edu.tw",
      messenger:"",
      schoolid: "50",
    },
    {
      id:"79",
      name:"明新科技大學",
      colorHead:"#DED5C6",
      colorEnd: "#F6F1EB",
      type:"綜合展區",
      link:"https://student.overseas.ncnu.edu.tw/quota/index.html?school=91&group=all&keyword=&first-group=true&second-group=true&third-group=true",
      email:"oia@must.edu.tw",
      messenger:"",
      schoolid: "91",
    },
    {
      id:"80",
      name:"醒吾科技大學",
      colorHead:"#DED5C6",
      colorEnd: "#F6F1EB",
      type:"綜合展區",
      link:"https://student.overseas.ncnu.edu.tw/quota/index.html?school=C4&group=all&keyword=&first-group=true&second-group=true&third-group=true",
      email:"",
      messenger:"",
      schoolid: "C4",
    },
    {
      id:"81",
      name:"中原大學",
      colorHead:"#DED5C6",
      colorEnd: "#F6F1EB",
      type:"綜合展區",
      link:"https://student.overseas.ncnu.edu.tw/quota/index.html?school=61&group=all&keyword=&first-group=true&second-group=true&third-group=true",
      email:"cycuoverseas@gmail.com",
      messenger:"",
      schoolid: "61",
    }
  ]

for(let i = 0 ; i<81 ; i++){
    let school = document.getElementById(i+1);
    school.href = schoolList[i].link;
    school.target = "_blank";
}

